# This is a GitHub Actions workflow that generates documentation for the std-unsafe-doc project.

name: Generate Docs

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rust-src

      - name: Ensure sysroot
        run: rustup update nightly

      - name: Generate documentation
        run: cargo doc --no-deps

      - name: Commit and push docs
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add -A docs/
          git commit -m 'Update docs [ci skip]' || echo 'No changes to commit'
          git push
